version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jrContrucoes
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_DATABASE: jr_construcoes
      DB_USERNAME: root
      DB_PASSWORD: 1234
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - jrConstrcoes

  db:
    image: mysql:8
    container_name: db_jrConstrcoes
    environment:
      MYSQL_DATABASE: jr_construcoes
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - jrConstrcoes

networks:
  jrConstrcoes:
    driver: bridge